"""estructura_inicial_completa

Revision ID: 69e0650d631f
Revises: 
Create Date: 2026-05-13 17:59:45.743541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e0650d631f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cronogramas_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo_equipo', sa.String(length=50), nullable=True),
    sa.Column('frecuencia_dias', sa.Integer(), nullable=True),
    sa.Column('descripcion_tareas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronogramas_mantenimiento_id'), 'cronogramas_mantenimiento', ['id'], unique=False)
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=300), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('contacto', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('web', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruc')
    )
    op.create_index(op.f('ix_proveedores_id'), 'proveedores', ['id'], unique=False)
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=300), nullable=True),
    sa.Column('distrito', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('es_central', sa.Boolean(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_sedes_id'), 'sedes', ['id'], unique=False)
    op.create_table('centrales_telefonicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('extensiones_total', sa.Integer(), nullable=True),
    sa.Column('en_garantia', sa.Boolean(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centrales_telefonicas_id'), 'centrales_telefonicas', ['id'], unique=False)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('mantenimiento', 'soporte', 'licencia', 'servicio', 'alquiler', 'otro', name='tipocontrato'), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('vigente', 'por_vencer', 'vencido', 'rescindido', name='estadocontrato'), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=5), nullable=True),
    sa.Column('alerta_30', sa.Boolean(), nullable=True),
    sa.Column('alerta_15', sa.Boolean(), nullable=True),
    sa.Column('alerta_7', sa.Boolean(), nullable=True),
    sa.Column('archivo_url', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_table('dispositivos_red',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=200), nullable=True),
    sa.Column('serie', sa.String(length=200), nullable=True),
    sa.Column('ip_gestion', sa.String(length=20), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.Enum('operativo', 'degradado', 'fuera', 'mantenimiento', name='estadoservicio'), nullable=True),
    sa.Column('firmware', sa.String(length=50), nullable=True),
    sa.Column('fecha_compra', sa.DateTime(), nullable=True),
    sa.Column('garantia_hasta', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispositivos_red_id'), 'dispositivos_red', ['id'], unique=False)
    op.create_table('licencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('software', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('fabricante', sa.String(length=200), nullable=True),
    sa.Column('tipo_licencia', sa.String(length=100), nullable=True),
    sa.Column('cantidad_total', sa.Integer(), nullable=True),
    sa.Column('cantidad_usada', sa.Integer(), nullable=True),
    sa.Column('clave', sa.Text(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('orden_compra', sa.String(length=100), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('alerta_30', sa.Boolean(), nullable=True),
    sa.Column('alerta_15', sa.Boolean(), nullable=True),
    sa.Column('alerta_7', sa.Boolean(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licencias_id'), 'licencias', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('apellido', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=300), nullable=True),
    sa.Column('rol', sa.Enum('jefe', 'especialista', 'mesa_ayuda', 'alta_direccion', 'usuario_final', 'usuario_externo', name='rolusuario'), nullable=False),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('ldap_dn', sa.String(length=500), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('turno', sa.Enum('manana', 'tarde', 'noche', name='turnotecnico'), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('carga_maxima', sa.Integer(), nullable=True, server_default='10'),
    sa.Column('creado_en', sa.DateTime(), nullable=True, server_default=sa.text('now()')),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('articulos_kb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=300), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'publicado', 'archivado', name='estadoarticulo'), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('vistas', sa.Integer(), nullable=True),
    sa.Column('util_si', sa.Integer(), nullable=True),
    sa.Column('util_no', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articulos_kb_id'), 'articulos_kb', ['id'], unique=False)
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_inventario', sa.String(length=50), nullable=False),
    sa.Column('codigo_patrimonial', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.Enum('pc_escritorio', 'laptop', 'servidor', 'impresora', 'switch', 'router', 'firewall', 'access_point', 'ups', 'proyector', 'telefono_ip', 'celular', 'tablet', 'scanner', 'otro', name='tipoequipo'), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=200), nullable=True),
    sa.Column('serie', sa.String(length=200), nullable=True),
    sa.Column('procesador', sa.String(length=200), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('disco_gb', sa.Integer(), nullable=True),
    sa.Column('pantalla_pulgadas', sa.Float(), nullable=True),
    sa.Column('sistema_operativo', sa.String(length=100), nullable=True),
    sa.Column('office_version', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=20), nullable=True),
    sa.Column('ip_asignada', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'en_mantenimiento', 'en_reparacion', 'de_baja', 'bodega', 'robado_perdido', name='estadoequipo'), nullable=True),
    sa.Column('usuario_asignado_id', sa.Integer(), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion_fisica', sa.String(length=200), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('orden_compra', sa.String(length=100), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('valor_compra', sa.Float(), nullable=True),
    sa.Column('vida_util_anios', sa.Integer(), nullable=True),
    sa.Column('valor_residual', sa.Float(), nullable=True),
    sa.Column('garantia_hasta', sa.Date(), nullable=True),
    sa.Column('poliza_seguro', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['usuario_asignado_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_patrimonial')
    )
    op.create_index(op.f('ix_equipos_codigo_inventario'), 'equipos', ['codigo_inventario'], unique=True)
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.create_index(op.f('ix_equipos_serie'), 'equipos', ['serie'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('ticket_nuevo', 'ticket_asignado', 'ticket_actualizado', 'ticket_resuelto', 'sla_por_vencer', 'sla_vencido', 'licencia_por_vencer', 'mantenimiento_prog', 'backup_fallido', 'contrato_por_vencer', 'sistema', name='tiponotificacion'), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_id'), 'notificaciones', ['id'], unique=False)
    op.create_table('politicas_backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('servidor', sa.String(length=200), nullable=True),
    sa.Column('ruta_origen', sa.String(length=300), nullable=True),
    sa.Column('ruta_destino', sa.String(length=300), nullable=True),
    sa.Column('tipo', sa.Enum('full', 'incremental', 'diferencial', name='tipobackup'), nullable=True),
    sa.Column('frecuencia', sa.String(length=50), nullable=True),
    sa.Column('hora_ejecucion', sa.Time(), nullable=True),
    sa.Column('retencion_dias', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_politicas_backup_id'), 'politicas_backup', ['id'], unique=False)
    op.create_table('servidores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('hostname', sa.String(length=200), nullable=True),
    sa.Column('ip_gestion', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.Enum('fisico', 'virtual', 'nube', name='tiposervidor'), nullable=True),
    sa.Column('sistema_operativo', sa.String(length=100), nullable=True),
    sa.Column('version_so', sa.String(length=50), nullable=True),
    sa.Column('cpu_nucleos', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('disco_total_tb', sa.Float(), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('rack', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.Enum('operativo', 'degradado', 'fuera', 'mantenimiento', name='estadoservicio'), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('servicios', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_index(op.f('ix_servidores_id'), 'servidores', ['id'], unique=False)
    op.create_table('solicitudes_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('equipo_nuevo', 'repuesto', 'licencia', 'servicio', 'renovacion', 'otro', name='tiposolicitud'), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'enviada', 'aprobada', 'rechazada', 'en_cotizacion', 'en_proceso', 'recibida', 'cancelada', name='estadosolicitud'), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('justificacion', sa.Text(), nullable=True),
    sa.Column('especificaciones', sa.Text(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('aprobador_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('valor_estimado', sa.Float(), nullable=True),
    sa.Column('valor_aprobado', sa.Float(), nullable=True),
    sa.Column('valor_final', sa.Float(), nullable=True),
    sa.Column('moneda', sa.String(length=5), nullable=True),
    sa.Column('presupuesto_codigo', sa.String(length=100), nullable=True),
    sa.Column('orden_compra_numero', sa.String(length=100), nullable=True),
    sa.Column('fecha_necesidad', sa.Date(), nullable=True),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprobador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_solicitudes_compra_id'), 'solicitudes_compra', ['id'], unique=False)
    op.create_table('asignaciones_licencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('licencia_id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['licencia_id'], ['licencias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_licencia_id'), 'asignaciones_licencia', ['id'], unique=False)
    op.create_table('bases_datos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('motor', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('servidor_id', sa.Integer(), nullable=True),
    sa.Column('puerto', sa.Integer(), nullable=True),
    sa.Column('sistema_info', sa.String(length=200), nullable=True),
    sa.Column('tamanio_gb', sa.Float(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['servidor_id'], ['servidores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bases_datos_id'), 'bases_datos', ['id'], unique=False)
    op.create_table('ejecuciones_backup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politica_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('exitoso', 'fallido', 'parcial', 'corriendo', 'cancelado', name='estadobackup'), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('tamanio_gb', sa.Float(), nullable=True),
    sa.Column('archivos_total', sa.Integer(), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=500), nullable=True),
    sa.Column('hash_md5', sa.String(length=64), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('fecha_verificacion', sa.DateTime(), nullable=True),
    sa.Column('verificado_por_id', sa.Integer(), nullable=True),
    sa.Column('resultado_verificacion', sa.Text(), nullable=True),
    sa.Column('alertado', sa.Boolean(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['politica_id'], ['politicas_backup.id'], ),
    sa.ForeignKeyConstraint(['verificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ejecuciones_backup_id'), 'ejecuciones_backup', ['id'], unique=False)
    op.create_table('items_solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_solicitud_id'), 'items_solicitud', ['id'], unique=False)
    op.create_table('lineas_telefonicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('tipo', sa.Enum('fija', 'celular', 'voip', 'fax', name='tipolinea'), nullable=True),
    sa.Column('operador', sa.String(length=100), nullable=True),
    sa.Column('plan', sa.String(length=200), nullable=True),
    sa.Column('costo_mensual', sa.Float(), nullable=True),
    sa.Column('asignado_a_id', sa.Integer(), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('es_directivo', sa.Boolean(), nullable=True),
    sa.Column('fecha_asignacion', sa.Date(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('equipo_celular', sa.String(length=200), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_a_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_lineas_telefonicas_id'), 'lineas_telefonicas', ['id'], unique=False)
    op.create_table('movimientos_equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('usuario_origen_id', sa.Integer(), nullable=True),
    sa.Column('usuario_destino_id', sa.Integer(), nullable=True),
    sa.Column('sede_origen_id', sa.Integer(), nullable=True),
    sa.Column('sede_destino_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('acta_numero', sa.String(length=100), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sede_destino_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['sede_origen_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['usuario_destino_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_origen_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_equipo_id'), 'movimientos_equipo', ['id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.Enum('critica', 'alta', 'media', 'baja', name='prioridadticket'), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'asignado', 'en_progreso', 'pendiente', 'escalado', 'resuelto', 'cerrado', 'cancelado', name='estadoticket'), nullable=False),
    sa.Column('categoria', sa.Enum('hardware', 'software', 'red', 'acceso', 'vpn', 'correo', 'impresora', 'telefonia', 'servidor', 'seguridad', 'mantenimiento', 'otro', name='categoriaticket'), nullable=True),
    sa.Column('canal_entrada', sa.Enum('portal', 'correo', 'whatsapp', 'llamada', 'sistema', name='canalentrada'), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_nivel2_id', sa.Integer(), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('asignado_en', sa.DateTime(), nullable=True),
    sa.Column('resuelto_en', sa.DateTime(), nullable=True),
    sa.Column('cerrado_en', sa.DateTime(), nullable=True),
    sa.Column('sla_limite', sa.DateTime(), nullable=True),
    sa.Column('sla_cumplido', sa.Boolean(), nullable=True),
    sa.Column('tiempo_resolucion_h', sa.Float(), nullable=True),
    sa.Column('solucion', sa.Text(), nullable=True),
    sa.Column('articulo_kb_id', sa.Integer(), nullable=True),
    sa.Column('nps_enviado', sa.Boolean(), nullable=True),
    sa.Column('nps_puntuacion', sa.Integer(), nullable=True),
    sa.Column('nps_comentario', sa.Text(), nullable=True),
    sa.Column('email_message_id', sa.String(length=300), nullable=True),
    sa.Column('email_asunto', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['articulo_kb_id'], ['articulos_kb.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tecnico_nivel2_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_numero'), 'tickets', ['numero'], unique=True)
    op.create_table('adjuntos_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=True),
    sa.Column('ruta', sa.String(length=500), nullable=True),
    sa.Column('tipo_mime', sa.String(length=100), nullable=True),
    sa.Column('tamanio_kb', sa.Integer(), nullable=True),
    sa.Column('subido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adjuntos_ticket_id'), 'adjuntos_ticket', ['id'], unique=False)
    op.create_table('comentarios_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('es_interno', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_ticket_id'), 'comentarios_ticket', ['id'], unique=False)
    op.create_table('historial_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('campo', sa.String(length=100), nullable=True),
    sa.Column('valor_anterior', sa.String(length=300), nullable=True),
    sa.Column('valor_nuevo', sa.String(length=300), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_ticket_id'), 'historial_ticket', ['id'], unique=False)
    op.create_table('ordenes_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('preventivo', 'correctivo', name='tipomantenimiento'), nullable=False),
    sa.Column('origen', sa.Enum('manual', 'automatico', 'ticket', name='origenorden'), nullable=True),
    sa.Column('estado', sa.Enum('programado', 'en_proceso', 'completado', 'cancelado', 'postergado', name='estadoorden'), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('ticket_origen_id', sa.Integer(), nullable=True),
    sa.Column('cronograma_id', sa.Integer(), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('trabajos_realizados', sa.Text(), nullable=True),
    sa.Column('repuestos_usados', sa.Text(), nullable=True),
    sa.Column('proxima_fecha', sa.Date(), nullable=True),
    sa.Column('requiere_baja', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cronograma_id'], ['cronogramas_mantenimiento.id'], ),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ticket_origen_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_index(op.f('ix_ordenes_mantenimiento_id'), 'ordenes_mantenimiento', ['id'], unique=False)
    op.create_table('checklist_mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('tarea', sa.String(length=300), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_mantenimiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_mantenimiento_id'), 'checklist_mantenimiento', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_mantenimiento_id'), table_name='checklist_mantenimiento')
    op.drop_table('checklist_mantenimiento')
    op.drop_index(op.f('ix_ordenes_mantenimiento_id'), table_name='ordenes_mantenimiento')
    op.drop_table('ordenes_mantenimiento')
    op.drop_index(op.f('ix_historial_ticket_id'), table_name='historial_ticket')
    op.drop_table('historial_ticket')
    op.drop_index(op.f('ix_comentarios_ticket_id'), table_name='comentarios_ticket')
    op.drop_table('comentarios_ticket')
    op.drop_index(op.f('ix_adjuntos_ticket_id'), table_name='adjuntos_ticket')
    op.drop_table('adjuntos_ticket')
    op.drop_index(op.f('ix_tickets_numero'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_movimientos_equipo_id'), table_name='movimientos_equipo')
    op.drop_table('movimientos_equipo')
    op.drop_index(op.f('ix_lineas_telefonicas_id'), table_name='lineas_telefonicas')
    op.drop_table('lineas_telefonicas')
    op.drop_index(op.f('ix_items_solicitud_id'), table_name='items_solicitud')
    op.drop_table('items_solicitud')
    op.drop_index(op.f('ix_ejecuciones_backup_id'), table_name='ejecuciones_backup')
    op.drop_table('ejecuciones_backup')
    op.drop_index(op.f('ix_bases_datos_id'), table_name='bases_datos')
    op.drop_table('bases_datos')
    op.drop_index(op.f('ix_asignaciones_licencia_id'), table_name='asignaciones_licencia')
    op.drop_table('asignaciones_licencia')
    op.drop_index(op.f('ix_solicitudes_compra_id'), table_name='solicitudes_compra')
    op.drop_table('solicitudes_compra')
    op.drop_index(op.f('ix_servidores_id'), table_name='servidores')
    op.drop_table('servidores')
    op.drop_index(op.f('ix_politicas_backup_id'), table_name='politicas_backup')
    op.drop_table('politicas_backup')
    op.drop_index(op.f('ix_notificaciones_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_equipos_serie'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_codigo_inventario'), table_name='equipos')
    op.drop_table('equipos')
    op.drop_index(op.f('ix_articulos_kb_id'), table_name='articulos_kb')
    op.drop_table('articulos_kb')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_licencias_id'), table_name='licencias')
    op.drop_table('licencias')
    op.drop_index(op.f('ix_dispositivos_red_id'), table_name='dispositivos_red')
    op.drop_table('dispositivos_red')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_centrales_telefonicas_id'), table_name='centrales_telefonicas')
    op.drop_table('centrales_telefonicas')
    op.drop_index(op.f('ix_sedes_id'), table_name='sedes')
    op.drop_table('sedes')
    op.drop_index(op.f('ix_proveedores_id'), table_name='proveedores')
    op.drop_table('proveedores')
    op.drop_index(op.f('ix_cronogramas_mantenimiento_id'), table_name='cronogramas_mantenimiento')
    op.drop_table('cronogramas_mantenimiento')
    # ### end Alembic commands ###
